#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

source ${OPENSHIFT_DATA_DIR}.private

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "Starting Sidekiq worker..."
if [ -f "${OPENSHIFT_DATA_DIR}sidekiq.pid" ]; then
  kill $(cat "${OPENSHIFT_DATA_DIR}sidekiq.pid")
  rm "${OPENSHIFT_DATA_DIR}sidekiq.pid"
fi

bundle exec 'sidekiq -d -c 5 -P "${OPENSHIFT_DATA_DIR}sidekiq.pid" -L "${OPENSHIFT_DATA_DIR}sidekiq.log"'
popd > /dev/null